### ISSUE TITLE
Flymake now support margins into core

### ISSUE THREAD

**Issue by DevelopmentCool2449** [LionyxML/flymake-margin#2]
Hello, i just i want to say that flymake now supports margins as indicator and
it will come into emacs 30.
I liked that you made a package from a little hack that i posted a few weeks ago, thank you :)
i used some features from this package as model for the patch.

You can check it here: https://github.com/emacs-mirror/emacs/commit/3c4f6c78b4b2ae0b1efadf5e664fa180e663037e

**Comment by LionyxML** [comment]
My pleasure @DevelopmentCool2449!

Really nice news this is going into Emacs.! I think I can finally rely on flymake alone on both gui and terminal.

If this is going to be part of Emacs after version 30, I guess I can put a version constrain into this package to push future use to the native implementation.

At the same time, keeping this on melpa will be usefull for those on versions before 29.X.

As soon as I have some time I'll make these changes and public announce the package :)
